#!/usr/bin/env python3
"""
Conditional 3D calibration surface for Polymarket BTC 5-minute UP/DOWN markets.

This version does NOT use Plotly. It writes one standalone HTML file that uses
Apache ECharts + ECharts-GL for the 3D surface rendering.

For each time remaining T and BTC threshold Y the surface answers:

    "Given the BTC price change condition is already met at time T, what is the
     historical probability that the market ends UP?"

The Z-axis represents a directional conditional probability:

    For Y >= 0 (upward threshold):
        realized[Y, T] = P(UP | BTC Δ >= Y, time T)
                       = #{UP markets with BTC Δ >= Y at T}
                         / #{all markets with BTC Δ >= Y at T}

    For Y < 0 (downward threshold):
        realized[Y, T] = P(UP | BTC Δ <= Y, time T)
                       = #{UP markets with BTC Δ <= Y at T}
                         / #{all markets with BTC Δ <= Y at T}

A strong positive move (large Y) → high UP probability.
A strong negative move (large |Y|) → low UP probability.

Gaussian smoothing is applied to numerator and denominator separately
to fill sparse tails without distorting interior probabilities.

The implied surface uses the same matching set:

    implied[Y, T] = avg(implied_prob | same condition as realized)

Gap:

    gap[Y, T] = realized[Y, T] - implied[Y, T]

By default implied uses all quoted markets. Pass --implied-universe up-only to
restrict to eventual-UP markets only.

Output
------
    docs/up_cumulative_echarts3d.html

Why this module exists
----------------------
Plotly 3D Surface hover templating can render literal placeholders like "%{text}" or
"%{customdata[2]:.4f}" in some browser/version combinations. This module avoids that
path entirely. ECharts tooltip text is generated by a normal JavaScript formatter.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Iterable, Literal

import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
PARQUET = Path("data/processed/btc_5m_timeseries.parquet")
DOCS = Path("docs")
OUT_HTML = "up_cumulative_echarts3d.html"

MARKET_SECONDS = 300
Y_MIN, Y_MAX = -0.50, 0.40          # percent units, not decimals
BUCKET_WIDTH_DEFAULT = 0.01          # percentage points; -0.50..+0.40 gives 91 thresholds
TIME_STEP_DEFAULT = 5                # displayed time_remaining spacing in seconds

# sigma_y fills sparse extreme buckets so the surface reaches 0 and 1 at the tails.
# sigma_t reduces per-time-step noise.  Use 0 for completely raw surfaces.
SIGMA_Y = 5.0
SIGMA_T = 2.0

BG = "#0f172a"

ID_CANDIDATES = (
    "event_timestamp",   # common in this BTC dataset
    "market_id",
    "condition_id",
    "question_id",
    "market_slug",
    "slug",
    "event_slug",
    "ticker",
    "id",
)

ImpliedUniverse = Literal["all", "up-only"]


# ---------------------------------------------------------------------------
# Parquet helpers
# ---------------------------------------------------------------------------
def parquet_columns(path: Path) -> list[str]:
    """Return parquet column names without loading the full dataset."""
    if not path.exists():
        raise FileNotFoundError(f"Parquet file not found: {path}")

    try:
        import pyarrow.parquet as pq  # type: ignore

        return list(pq.ParquetFile(path).schema.names)
    except Exception:
        try:
            import fastparquet  # type: ignore

            return list(fastparquet.ParquetFile(path).columns)
        except Exception as exc:
            raise RuntimeError(
                "Could not inspect parquet columns. Install pyarrow or fastparquet."
            ) from exc


def first_existing(columns: Iterable[str], candidates: Iterable[str]) -> str | None:
    colset = set(columns)
    for c in candidates:
        if c in colset:
            return c
    return None


def require_col(columns: Iterable[str], name: str) -> str:
    if name not in set(columns):
        raise ValueError(f"Required column not found: {name!r}")
    return name


def detect_id_col(columns: list[str], requested: str | None) -> str:
    if requested:
        return require_col(columns, requested)

    detected = first_existing(columns, ID_CANDIDATES)
    if detected is None:
        raise ValueError(
            "Could not detect a market/event id column. Pass --id-col explicitly. "
            f"Available columns: {columns}"
        )
    return detected


# ---------------------------------------------------------------------------
# Data loading / normalization
# ---------------------------------------------------------------------------
def normalize_implied_prob(s: pd.Series, scale: str) -> pd.Series:
    """
    Return implied probability in [0, 1].

    scale="prob"    -> input already 0..1
    scale="percent" -> input is 0..100
    scale="auto"    -> divide by 100 only if values look like percentages
    """
    out = pd.to_numeric(s, errors="coerce").astype(float)

    if scale == "percent":
        out = out / 100.0
    elif scale == "auto":
        finite = out[np.isfinite(out)]
        if len(finite) > 0:
            q99 = float(finite.quantile(0.99))
            max_v = float(finite.max())
            if q99 > 1.01 and max_v <= 100.0:
                print("  Detected implied_prob values that look like percentages; dividing by 100.")
                out = out / 100.0
    elif scale != "prob":
        raise ValueError("--implied-scale must be one of: auto, prob, percent")

    return out.clip(lower=0.0, upper=1.0)


def load_data(
    parquet: Path,
    *,
    id_col: str | None,
    second_col: str,
    btc_col: str,
    implied_col: str,
    winner_col: str,
    market_seconds: int,
    time_step: int,
    engine: str,
    implied_scale: str,
    skip_first: int = 0,
) -> tuple[pd.DataFrame, int, str]:
    print("Loading data ...", flush=True)

    cols = parquet_columns(parquet)
    id_col = detect_id_col(cols, id_col)
    for c in (second_col, btc_col, implied_col, winner_col):
        require_col(cols, c)

    read_cols = [id_col, second_col, btc_col, implied_col, winner_col]
    df = pd.read_parquet(parquet, columns=read_cols, engine=engine)
    df = df.rename(
        columns={
            id_col: "market_id",
            second_col: "second",
            btc_col: "btc_pct_change",
            implied_col: "implied_prob",
            winner_col: "winner_binary",
        }
    )

    # Keep missing btc/implied rows for now. Realized and implied surfaces have separate
    # finite-value masks later. Missing implied_prob must not delete realized observations.
    df["second"] = pd.to_numeric(df["second"], errors="coerce")
    df["btc_pct_change"] = pd.to_numeric(df["btc_pct_change"], errors="coerce")
    df["implied_prob"] = normalize_implied_prob(df["implied_prob"], implied_scale)
    df["winner_binary"] = pd.to_numeric(df["winner_binary"], errors="coerce")

    df = df.dropna(subset=["market_id", "second", "winner_binary"])
    df = df[df["winner_binary"].isin([0, 1])].copy()
    df["second"] = np.rint(df["second"]).astype(np.int16)
    df = df[(df["second"] >= 0) & (df["second"] <= market_seconds)].copy()

    if df.empty:
        raise ValueError("No usable rows after basic cleaning.")

    # Resolve one final outcome per market. winner_binary should already be fixed, but max()
    # protects against duplicate/inconsistent rows.
    outcome_by_market = df.groupby("market_id", sort=False)["winner_binary"].max().astype(np.int8)

    # Skip the earliest N markets (sorted by market_id, which is event_timestamp).
    if skip_first > 0:
        ordered_ids = outcome_by_market.index.sort_values()
        if skip_first >= len(ordered_ids):
            raise ValueError(
                f"--skip-first {skip_first} ≥ total markets {len(ordered_ids)}; nothing left."
            )
        keep_ids = set(ordered_ids[skip_first:])
        df = df[df["market_id"].isin(keep_ids)].copy()
        outcome_by_market = outcome_by_market[outcome_by_market.index.isin(keep_ids)]
        print(f"  Skipped first {skip_first:,} markets (oldest by event_timestamp); "
              f"{len(keep_ids):,} markets remaining.")

    total_up = int((outcome_by_market == 1).sum())
    if total_up <= 0:
        raise ValueError("No eventual-UP markets found; total_up is zero.")

    df["winner_binary"] = df["market_id"].map(outcome_by_market).astype(np.int8)

    # One coherent observation per market per second. drop_duplicates(keep="last") keeps the
    # last full row, instead of groupby.last(), which can mix columns from different rows.
    df = df.sort_values(["market_id", "second"], kind="mergesort")
    df = df.drop_duplicates(["market_id", "second"], keep="last").copy()

    df["time_remaining"] = (market_seconds - df["second"]).astype(np.int16)

    # Keep the displayed time grid exactly aligned to requested time_remaining buckets.
    df = df[df["time_remaining"] % time_step == 0].copy()

    n_markets = int(outcome_by_market.shape[0])
    print(f"  ID column: {id_col}")
    print(f"  Unique markets: {n_markets:,}")
    print(f"  Eventual-UP markets / denominator: {total_up:,}")
    print(f"  Rows after de-dup/time filter: {len(df):,}")
    print(f"  Displayed time steps with at least one row: {df['time_remaining'].nunique():,}")

    return df, total_up, id_col


# ---------------------------------------------------------------------------
# Grid and surfaces
# ---------------------------------------------------------------------------
def make_y_grid(y_min: float, y_max: float, bucket_width: float) -> np.ndarray:
    if bucket_width <= 0:
        raise ValueError("--bucket-width must be positive")
    if y_min >= y_max:
        raise ValueError("--y-min must be smaller than --y-max")

    n = int(round((y_max - y_min) / bucket_width)) + 1
    y = y_min + np.arange(n, dtype=float) * bucket_width
    y[-1] = y_max
    return np.round(y, 10)


def make_t_grid(market_seconds: int, time_step: int) -> list[int]:
    if time_step <= 0:
        raise ValueError("--time-step must be positive")
    return list(range(market_seconds, -1, -time_step))


def directional_by_threshold(
    values: np.ndarray,
    weights: np.ndarray,
    y_grid: np.ndarray,
) -> np.ndarray:
    """
    Directional tail count for P(UP | condition already met at time T).

    For each grid point y:
      - y >= 0:  out[i] = sum(weights where value >= y)   (right-tail / up-exceedance)
      - y <  0:  out[i] = sum(weights where value <= y)   (left-tail  / down-exceedance)

    This answers "given BTC has already moved at least Y, how often does it end UP?".
    The surface is monotone: strong up move → high UP probability, strong down → low.
    """
    if len(values) == 0:
        return np.zeros(len(y_grid), dtype=float)

    values  = np.asarray(values,  dtype=float)
    weights = np.asarray(weights, dtype=float)
    finite  = np.isfinite(values) & np.isfinite(weights)
    if not np.any(finite):
        return np.zeros(len(y_grid), dtype=float)

    clipped = np.clip(values[finite], y_grid[0], y_grid[-1])
    w       = weights[finite]

    # Per-bucket counts (base counts for cumsum tricks)
    idx = np.searchsorted(y_grid, clipped, side="right") - 1
    idx = np.clip(idx, 0, len(y_grid) - 1)
    per_bucket = np.zeros(len(y_grid), dtype=float)
    np.add.at(per_bucket, idx, w)

    # Left-tail cumsum: left_cs[i] = sum of per_bucket[0..i]  (value <= y_grid[i])
    left_cs  = np.cumsum(per_bucket)
    # Right-tail cumsum: right_cs[i] = sum of per_bucket[i..end]  (value >= y_grid[i])
    right_cs = np.cumsum(per_bucket[::-1])[::-1]

    # Directional selection: >= for positive thresholds, <= for negative
    return np.where(y_grid >= 0, right_cs, left_cs)


def build_surfaces(
    df: pd.DataFrame,
    y_grid: np.ndarray,
    t_vals: list[int],
    *,
    implied_universe: ImpliedUniverse,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Compute directional tail-count surfaces for conditional probability.

    For each threshold Y and time T:
      - Y >= 0:  Z_up[Y,T]  = #{UP markets with BTC Δ >= Y at T}
                 Z_all[Y,T] = #{all markets with BTC Δ >= Y at T}
      - Y <  0:  Z_up[Y,T]  = #{UP markets with BTC Δ <= Y at T}
                 Z_all[Y,T] = #{all markets with BTC Δ <= Y at T}

    After Gaussian smoothing:
        Realized[Y, T] = smooth(Z_up) / smooth(Z_all)  = P(UP | condition met, T)
        Implied[Y, T]  = smooth(Z_isum) / smooth(Z_icnt)
        Gap[Y, T]      = Realized - Implied
    """
    n_y = len(y_grid)
    n_t = len(t_vals)

    Z_up   = np.zeros((n_y, n_t), dtype=float)
    Z_all  = np.zeros((n_y, n_t), dtype=float)
    Z_isum = np.zeros((n_y, n_t), dtype=float)
    Z_icnt = np.zeros((n_y, n_t), dtype=float)

    print("Computing directional conditional probability surfaces ...", flush=True)

    grouped = {int(t): g for t, g in df.groupby("time_remaining", sort=False)}
    ones = np.ones

    for t_idx, T in enumerate(t_vals):
        grp = grouped.get(T)
        if grp is None or grp.empty:
            continue

        all_m = grp[np.isfinite(grp["btc_pct_change"])]
        if not all_m.empty:
            vals = all_m["btc_pct_change"].to_numpy(float)
            Z_all[:, t_idx] = directional_by_threshold(vals, ones(len(vals)), y_grid)

        up = grp[(grp["winner_binary"] == 1) & np.isfinite(grp["btc_pct_change"])]
        if not up.empty:
            vals = up["btc_pct_change"].to_numpy(float)
            Z_up[:, t_idx] = directional_by_threshold(vals, ones(len(vals)), y_grid)

        if implied_universe == "up-only":
            impl_grp = grp[grp["winner_binary"] == 1]
        elif implied_universe == "all":
            impl_grp = grp
        else:
            raise ValueError("implied_universe must be 'all' or 'up-only'.")

        impl_grp = impl_grp[
            np.isfinite(impl_grp["btc_pct_change"]) & np.isfinite(impl_grp["implied_prob"])
        ]
        if not impl_grp.empty:
            vals  = impl_grp["btc_pct_change"].to_numpy(float)
            probs = impl_grp["implied_prob"].to_numpy(float)
            Z_isum[:, t_idx] = directional_by_threshold(vals, probs, y_grid)
            Z_icnt[:, t_idx] = directional_by_threshold(vals, ones(len(vals)), y_grid)

    # At Y=0 the right-tail count equals all markets with BTC Δ >= 0 (roughly half).
    # The maximum count across Y occurs at the most inclusive threshold.
    # For positive side: y_grid[first non-negative idx] has the highest right-tail count.
    # For coverage purposes use the Y=0 column (most populated for both directions).
    zero_idx = int(np.searchsorted(y_grid, 0.0, side="left"))
    total_markets = int(Z_all[zero_idx, :].max())
    total_up_peak = int(Z_up[zero_idx, :].max())
    print(f"  Grid: {n_y:,} thresholds x {n_t:,} time steps")
    print(f"  Peak all-markets count (at Y=0): {total_markets:,}")
    print(f"  Peak UP-markets count  (at Y=0): {total_up_peak:,}")

    return Z_up, Z_isum, Z_icnt, Z_all


# ---------------------------------------------------------------------------
# Smoothing for conditional probability surfaces
# ---------------------------------------------------------------------------
def smooth_and_divide(
    numerator: np.ndarray,
    denominator: np.ndarray,
    sigma_y: float,
    sigma_t: float,
    min_denom: float = 0.5,
) -> np.ndarray:
    """
    Robustly smooth a conditional probability surface from sparse count data.

    Instead of smoothing the ratio (which amplifies noise in sparse buckets),
    smooth numerator and denominator independently with a Gaussian kernel,
    then divide.  This is equivalent to kernel density estimation and gives
    stable probabilities even where individual buckets have < 5 markets.

    Cells where the smoothed denominator is below `min_denom` are set to NaN
    (treated as no data rather than a noisy estimate).
    """
    num = np.nan_to_num(numerator.astype(float), nan=0.0)
    den = np.nan_to_num(denominator.astype(float), nan=0.0)

    if sigma_y > 0 or sigma_t > 0:
        sigma = (max(sigma_y, 0.0), max(sigma_t, 0.0))
        num = gaussian_filter(num, sigma=sigma, mode="nearest")
        den = gaussian_filter(den, sigma=sigma, mode="nearest")

    with np.errstate(invalid="ignore", divide="ignore"):
        result = np.where(den >= min_denom, num / den, np.nan)

    return np.clip(result, 0.0, 1.0)


# ---------------------------------------------------------------------------
# HTML / ECharts helpers
# ---------------------------------------------------------------------------
def round_float(x: float, ndigits: int = 6) -> float:
    if not np.isfinite(x):
        return 0.0
    return round(float(x), ndigits)


def matrix_to_surface_points(
    *,
    X: np.ndarray,
    Y: np.ndarray,
    Z_real: np.ndarray,
    Z_impl: np.ndarray,
    Z_gap: np.ndarray,
    Z_surface: np.ndarray,
    Z_up_count: np.ndarray,
    Z_all_count: np.ndarray,
    Z_impl_count: np.ndarray,
) -> list[list[float | int]]:
    """
    ECharts surface data points.

    Each point:
      [time_elapsed, y_upper, z_surface, realized, implied, gap,
       up_count_in_bucket, all_count_in_bucket, impl_count_in_bucket]

    X stores time_remaining (descending: 295…5).  The ECharts GL xAxis3D uses
    inverse: true so the display shows 295 on the left (market start) → 5 on
    the right (market end).
    """
    out: list[list[float | int]] = []
    for yi, y in enumerate(Y):
        for ti, t in enumerate(X):
            z_s  = Z_surface[yi, ti]
            z_r  = Z_real[yi, ti]
            z_i  = Z_impl[yi, ti]
            z_g  = Z_gap[yi, ti]
            out.append(
                [
                    int(t),   # time_remaining
                    round_float(float(y), 4),
                    round_float(float(z_s)  if np.isfinite(z_s)  else float("nan"), 6),
                    round_float(float(z_r)  if np.isfinite(z_r)  else float("nan"), 6),
                    round_float(float(z_i)  if np.isfinite(z_i)  else float("nan"), 6),
                    round_float(float(z_g)  if np.isfinite(z_g)  else float("nan"), 6),
                    int(round(float(Z_up_count[yi, ti]))),
                    int(round(float(Z_all_count[yi, ti]))),
                    int(round(float(Z_impl_count[yi, ti]))),
                ]
            )
    return out


def surface_payload(
    *,
    X: np.ndarray,
    Y: np.ndarray,
    Z_real_s: np.ndarray,
    Z_impl_s: np.ndarray,
    Z_gap: np.ndarray,
    Z_up_count: np.ndarray,
    Z_all_count: np.ndarray,
    Z_impl_count: np.ndarray,
    total_up: int,
    market_seconds: int,
    implied_universe: str,
    bucket_width: float,
) -> dict:
    # Stretch the gap z-axis to the actual data range so the surface fills the box.
    finite_gap = Z_gap[np.isfinite(Z_gap)]
    gap_abs = max(abs(float(finite_gap.min())), abs(float(finite_gap.max())), 0.01) if finite_gap.size else 0.1
    gap_range = round(gap_abs * 1.15, 4)   # 15% headroom

    # ECharts GL surface grid auto-detection requires ascending X values.
    # X is time_remaining descending [295…5]; reverse it and flip the T axis of
    # all Z arrays so data is ascending [5…295].  The xAxis3D uses inverse:true
    # to display 295 on the left (market start) → 5 on the right (market end).
    X_asc = X[::-1]
    shared_points_kw = dict(
        X=X_asc, Y=Y,
        Z_real=Z_real_s[:, ::-1], Z_impl=Z_impl_s[:, ::-1], Z_gap=Z_gap[:, ::-1],
        Z_up_count=Z_up_count[:, ::-1], Z_all_count=Z_all_count[:, ::-1],
        Z_impl_count=Z_impl_count[:, ::-1],
    )
    return {
        "meta": {
            "totalUp": int(total_up),
            "marketSeconds": int(market_seconds),
            "impliedUniverse": implied_universe,
            "nTime": int(len(X_asc)),
            "nY": int(len(Y)),
            "timeMin": int(np.min(X_asc)),
            "timeMax": int(np.max(X_asc)),
            "yMin": float(np.min(Y)),
            "yMax": float(np.max(Y)),
            "bucketWidth": float(bucket_width),
        },
        "datasets": {
            "realized": {
                "title": "Realized — P(UP | BTC move condition met at time T)",
                "subtitle": "Y>0: P(UP|BTC Δ≥Y,T)  ·  Y<0: P(UP|BTC Δ≤Y,T)  ·  Gaussian-smoothed",
                "zName": "Realized P(UP)",
                "zMin": 0,
                "zMax": 1,
                "visualMin": 0,
                "visualMax": 1,
                "palette": "prob",
                "data": matrix_to_surface_points(
                    **shared_points_kw, Z_surface=Z_real_s[:, ::-1],
                ),
            },
            "implied": {
                "title": "Implied — avg market-quoted P(UP | BTC move condition met at time T)",
                "subtitle": "avg(implied_prob) over same directional matching set as realized",
                "zName": "Implied P(UP)",
                "zMin": 0,
                "zMax": 1,
                "visualMin": 0,
                "visualMax": 1,
                "palette": "prob",
                "data": matrix_to_surface_points(
                    **shared_points_kw, Z_surface=Z_impl_s[:, ::-1],
                ),
            },
            "gap": {
                "title": "Calibration gap: realized − implied",
                "subtitle": "Green = market under-prices UP  |  red = over-prices UP",
                "zName": "Realized − Implied gap",
                "zMin": -gap_range,
                "zMax": gap_range,
                "visualMin": -gap_range,
                "visualMax": gap_range,
                "palette": "gap",
                "data": matrix_to_surface_points(
                    **shared_points_kw, Z_surface=Z_gap[:, ::-1],
                ),
            },
        },
    }


def build_html(payload: dict) -> str:
    payload_json = json.dumps(payload, separators=(",", ":"), ensure_ascii=False)
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>UP cumulative 3D calibration surfaces</title>
  <script src="https://cdn.jsdelivr.net/npm/echarts@5.5.1/dist/echarts.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/echarts-gl@2.0.9/dist/echarts-gl.min.js"></script>
  <style>
    :root {{
      --bg: {BG};
      --panel: #111827;
      --panel2: #1f2937;
      --text: #e5e7eb;
      --muted: #94a3b8;
      --border: #334155;
      --accent: #38bdf8;
    }}
    html, body {{
      width: 100%;
      height: 100%;
      margin: 0;
      overflow: hidden;
      background: var(--bg);
      color: var(--text);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    #app {{
      width: 100%;
      height: 100%;
      display: grid;
      grid-template-rows: auto 1fr;
    }}
    #toolbar {{
      display: flex;
      gap: 12px;
      align-items: center;
      justify-content: space-between;
      padding: 12px 16px;
      background: rgba(15, 23, 42, 0.96);
      border-bottom: 1px solid var(--border);
      box-sizing: border-box;
      z-index: 2;
    }}
    #titleBlock {{ min-width: 0; }}
    #title {{
      font-size: 18px;
      font-weight: 700;
      line-height: 1.2;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }}
    #subtitle {{
      margin-top: 3px;
      font-size: 12px;
      color: var(--muted);
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }}
    #controls {{
      display: flex;
      gap: 8px;
      align-items: center;
      flex-wrap: wrap;
      justify-content: flex-end;
    }}
    button {{
      border: 1px solid var(--border);
      color: var(--text);
      background: var(--panel);
      padding: 8px 12px;
      border-radius: 999px;
      cursor: pointer;
      font-size: 13px;
    }}
    button:hover {{ border-color: var(--accent); }}
    button.active {{
      background: #0ea5e9;
      border-color: #7dd3fc;
      color: white;
    }}
    #chart {{ width: 100%; height: 100%; }}
    #note {{
      position: absolute;
      left: 16px;
      bottom: 12px;
      max-width: 760px;
      padding: 8px 10px;
      font-size: 12px;
      color: var(--muted);
      background: rgba(15, 23, 42, 0.74);
      border: 1px solid rgba(51, 65, 85, 0.8);
      border-radius: 10px;
      pointer-events: none;
    }}
  </style>
</head>
<body>
  <div id="app">
    <div id="toolbar">
      <div id="titleBlock">
        <div id="title">UP 3D calibration surfaces</div>
        <div id="subtitle">Loading...</div>
      </div>
      <div id="controls">
        <button data-mode="realized" class="active">Realized</button>
        <button data-mode="implied">Implied</button>
        <button data-mode="gap">Gap</button>
      </div>
    </div>
    <div id="chart"></div>
  </div>
  <div id="note">Drag to rotate · Scroll to zoom · Click Realized / Implied / Gap to switch views</div>

  <script id="surface-data" type="application/json">{payload_json}</script>
  <script>
    const PAYLOAD = JSON.parse(document.getElementById('surface-data').textContent);
    const chart = echarts.init(document.getElementById('chart'), null, {{ renderer: 'canvas' }});
    let currentMode = 'realized';

    function fmtPct(x) {{
      const sign = x >= 0 ? '+' : '';
      return sign + Number(x).toFixed(2) + '%';
    }}
    function fmt4(x) {{
      return Number(x).toFixed(4);
    }}
    function fmtSigned4(x) {{
      const sign = x >= 0 ? '+' : '';
      return sign + Number(x).toFixed(4);
    }}
    function fmtInt(x) {{
      return Math.round(Number(x)).toLocaleString();
    }}

    function colorsFor(ds) {{
      if (ds.palette === 'gap') {{
        // blue (under-pricing) → deep violet (neutral) → red (over-pricing) — no white so structure is visible
        return ['#1d4ed8', '#7c3aed', '#dc2626'];
      }}
      // red (P=0) → amber → green (P=1): traffic-light for cumulative UP probability
      return ['#dc2626', '#f59e0b', '#16a34a'];
    }}

    function tooltipFormatter(params) {{
      const v = params.value;
      // v = [time_remaining, y_threshold, z_surface, realized, implied, gap, matchCount, upCount, implCount]
      const time     = v[0];
      const y        = v[1];
      const realized = v[3];
      const implied  = v[4];
      const gap      = v[5];
      const matchAll = v[7];   // all markets where condition is met
      const matchUp  = v[6];   // UP markets where condition is met

      const bold = (s) => `<b>${{s}}</b>`;
      const r = currentMode === 'realized';
      const i = currentMode === 'implied';
      const g = currentMode === 'gap';

      const realFmt = isFinite(realized) ? fmt4(realized) : '—';
      const implFmt = isFinite(implied)  ? fmt4(implied)  : '—';
      const gapFmt  = isFinite(gap)      ? fmtSigned4(gap) : '—';

      // Show the directional condition
      const yFmt = fmtPct(y);
      const condition = y >= 0
        ? `BTC \u0394 \u2265 ${{yFmt}}`
        : `BTC \u0394 \u2264 ${{yFmt}}`;

      return `
        <div style="min-width:320px;line-height:1.7;font-size:12px">
          <div style="font-weight:700;margin-bottom:4px">P(UP | condition met at time T)</div>
          <div>Time remaining: <b>${{time}} s</b></div>
          <div>Condition: <b>${{condition}}</b></div>
          <hr style="border:none;border-top:1px solid #475569;margin:5px 0" />
          <div>Matching markets: <b>${{fmtInt(matchAll)}}</b></div>
          <div>UP outcomes: <b>${{fmtInt(matchUp)}}</b></div>
          <hr style="border:none;border-top:1px solid #475569;margin:5px 0" />
          <div>Realized P(UP): ${{r ? bold(realFmt) : realFmt}}</div>
          <div>Implied P(UP): ${{i ? bold(implFmt) : implFmt}}</div>
          <div>Gap (realized \u2212 implied): ${{g ? bold(gapFmt) : gapFmt}}</div>
        </div>
      `;
    }}

    function makeOption(mode) {{
      const ds = PAYLOAD.datasets[mode];
      const colors = colorsFor(ds);
      const titleText = ds.title;
      const subtitleText = `${{ds.subtitle}} · implied universe: ${{PAYLOAD.meta.impliedUniverse}}`;
      document.getElementById('title').textContent = titleText;
      document.getElementById('subtitle').textContent = subtitleText;

      const isGap = mode === 'gap';
      return {{
        backgroundColor: '{BG}',
        animation: false,
        tooltip: {{
          show: true,
          trigger: 'item',
          confine: true,
          backgroundColor: 'rgba(15, 23, 42, 0.96)',
          borderColor: '#475569',
          textStyle: {{ color: '#e5e7eb', fontSize: 12 }},
          formatter: tooltipFormatter,
        }},
        visualMap: {{
          show: true,
          calculable: true,
          realtime: false,
          dimension: 2,
          min: ds.visualMin,
          max: ds.visualMax,
          precision: 3,
          text: [String(ds.visualMax), String(ds.visualMin)],
          textStyle: {{ color: '#e5e7eb' }},
          inRange: {{ color: colors }},
          orient: 'vertical',
          right: 18,
          top: 86,
        }},
        xAxis3D: {{
          type: 'value',
          name: 'Time elapsed (s)',
          min: PAYLOAD.meta.timeMin,
          max: PAYLOAD.meta.timeMax,
          inverse: true,
          nameTextStyle: {{ color: '#e5e7eb' }},
          axisLabel: {{ color: '#cbd5e1', hideOverlap: true }},
          axisLine: {{ lineStyle: {{ color: '#94a3b8' }} }},
          splitLine: {{ lineStyle: {{ color: '#334155' }} }},
        }},
        yAxis3D: {{
          type: 'value',
          name: 'BTC Δ threshold (%)',
          min: PAYLOAD.meta.yMin,
          max: PAYLOAD.meta.yMax,
          nameTextStyle: {{ color: '#e5e7eb' }},
          axisLabel: {{
            color: '#cbd5e1',
            formatter: function(value) {{ return fmtPct(value); }}
          }},
          axisLine: {{ lineStyle: {{ color: '#94a3b8' }} }},
          splitLine: {{ lineStyle: {{ color: '#334155' }} }},
        }},
        zAxis3D: {{
          type: 'value',
          name: ds.zName,
          min: ds.zMin,
          max: ds.zMax,
          nameTextStyle: {{ color: '#e5e7eb' }},
          axisLabel: {{ color: '#cbd5e1' }},
          axisLine: {{ lineStyle: {{ color: '#94a3b8' }} }},
          splitLine: {{ lineStyle: {{ color: '#334155' }} }},
        }},
        grid3D: {{
          boxWidth: 160,
          boxDepth: 100,
          boxHeight: isGap ? 78 : 90,
          environment: '{BG}',
          axisPointer: {{ show: true }},
          viewControl: {{
            projection: 'perspective',
            autoRotate: false,
            alpha: 26,
            beta: -42,
            distance: 220,
            minDistance: 80,
            maxDistance: 420,
          }},
          light: {{
            main: {{ intensity: 1.2, shadow: false }},
            ambient: {{ intensity: 0.55 }},
          }},
          postEffect: {{ enable: false }},
          temporalSuperSampling: {{ enable: false }},
        }},
        series: [{{
          type: 'surface',
          name: ds.zName,
          data: ds.data,
          shading: 'color',
          wireframe: {{ show: false }},
          itemStyle: {{ opacity: 0.97 }},
          silent: false,
        }}]
      }};
    }}

    function setMode(mode) {{
      currentMode = mode;
      document.querySelectorAll('button[data-mode]').forEach(btn => {{
        btn.classList.toggle('active', btn.dataset.mode === mode);
      }});
      chart.setOption(makeOption(mode), true);
    }}

    document.querySelectorAll('button[data-mode]').forEach(btn => {{
      btn.addEventListener('click', () => setMode(btn.dataset.mode));
    }});

    window.addEventListener('resize', () => chart.resize());
    setMode(currentMode);
  </script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Diagnostics
# ---------------------------------------------------------------------------
def print_self_check(
    *,
    Z_real_s: np.ndarray,
    Z_impl_s: np.ndarray,
    Z_all_count: np.ndarray,
    Z_up_count: np.ndarray,
    coverage: np.ndarray,
) -> None:
    print("Self-check ...")

    fin_r = Z_real_s[np.isfinite(Z_real_s)]
    fin_i = Z_impl_s[np.isfinite(Z_impl_s)]

    print(f"  Smoothed realized: min={float(fin_r.min()):.4f}  max={float(fin_r.max()):.4f}  "
          f"mean={float(fin_r.mean()):.4f}  (cells with data: {fin_r.size:,})")
    print(f"  Smoothed implied:  min={float(fin_i.min()):.4f}  max={float(fin_i.max()):.4f}  "
          f"mean={float(fin_i.mean()):.4f}  (cells with data: {fin_i.size:,})")

    # Range check: conditional probabilities must be in [0, 1]
    for name, Z in (("realized", Z_real_s), ("implied", Z_impl_s)):
        fin = Z[np.isfinite(Z)]
        if fin.size and (float(fin.min()) < -1e-6 or float(fin.max()) > 1 + 1e-6):
            print(f"  WARNING: {name} has values outside [0, 1]: "
                  f"min={float(fin.min()):.6f}, max={float(fin.max()):.6f}")
        else:
            print(f"  Range check OK for {name}: values in [0, 1]")

    # Coverage
    print(f"  Coverage: max={float(coverage.max()):.4f}  min(nonzero)="
          f"{float(coverage[coverage > 0].min()) if np.any(coverage > 0) else 0:.4f}")

    # Bucket density: warn if very sparse
    mean_per_bucket = float(Z_all_count[Z_all_count > 0].mean()) if np.any(Z_all_count > 0) else 0
    print(f"  Mean markets per non-empty bucket: {mean_per_bucket:.1f}")
    if mean_per_bucket < 5:
        print("  NOTE: data is sparse per bucket — smoothing provides most of the density.")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="Build UP cumulative 3D calibration surface HTML with ECharts-GL.")
    parser.add_argument("--parquet", type=Path, default=PARQUET)
    parser.add_argument("--docs", type=Path, default=DOCS)
    parser.add_argument("--out", type=str, default=OUT_HTML, help="Output HTML filename inside --docs")
    parser.add_argument("--id-col", type=str, default=None, help="Market/event id column. Auto-detected if omitted.")
    parser.add_argument("--second-col", type=str, default="second")
    parser.add_argument("--btc-col", type=str, default="btc_pct_change")
    parser.add_argument("--implied-col", type=str, default="implied_prob")
    parser.add_argument("--winner-col", type=str, default="winner_binary")
    parser.add_argument("--engine", type=str, default="auto", help="pandas parquet engine: auto, pyarrow, or fastparquet")
    parser.add_argument(
        "--implied-scale",
        choices=["auto", "prob", "percent"],
        default="auto",
        help="Use 'prob' for 0..1, 'percent' for 0..100, or 'auto' to infer.",
    )
    parser.add_argument("--market-seconds", type=int, default=MARKET_SECONDS)
    parser.add_argument("--time-step", type=int, default=TIME_STEP_DEFAULT)
    parser.add_argument("--y-min", type=float, default=Y_MIN)
    parser.add_argument("--y-max", type=float, default=Y_MAX)
    parser.add_argument("--bucket-width", type=float, default=BUCKET_WIDTH_DEFAULT)
    parser.add_argument("--sigma-y", type=float, default=SIGMA_Y)
    parser.add_argument("--sigma-t", type=float, default=SIGMA_T)
    parser.add_argument(
        "--skip-first",
        type=int,
        default=0,
        help="Drop the N oldest prediction markets (by event_timestamp) before computing surfaces.",
    )
    parser.add_argument(
        "--implied-universe",
        choices=["all", "up-only"],
        default="all",
        help=(
            "Rows used for implied-probability mass. 'all' is the usual calibration comparison; "
            "'up-only' ignores eventual-DOWN markets even for implied mass."
        ),
    )
    args = parser.parse_args()

    if args.market_seconds <= 0:
        raise ValueError("--market-seconds must be positive")
    if args.time_step <= 0:
        raise ValueError("--time-step must be positive")
    if args.y_min >= args.y_max:
        raise ValueError("--y-min must be smaller than --y-max")

    print(
        f"Settings: y=[{args.y_min:+.2f}%, {args.y_max:+.2f}%], "
        f"bucket_width={args.bucket_width:.4f}%, time_step={args.time_step}s, "
        f"sigma=({args.sigma_y}, {args.sigma_t}), implied_universe={args.implied_universe}"
    )

    args.docs.mkdir(parents=True, exist_ok=True)

    df, total_up, _ = load_data(
        args.parquet,
        id_col=args.id_col,
        second_col=args.second_col,
        btc_col=args.btc_col,
        implied_col=args.implied_col,
        winner_col=args.winner_col,
        market_seconds=args.market_seconds,
        time_step=args.time_step,
        engine=args.engine,
        implied_scale=args.implied_scale,
        skip_first=args.skip_first,
    )

    y_grid = make_y_grid(args.y_min, args.y_max, args.bucket_width)
    t_vals = make_t_grid(args.market_seconds, args.time_step)

    Z_up, Z_isum, Z_icnt, Z_all = build_surfaces(
        df,
        y_grid,
        t_vals,
        implied_universe=args.implied_universe,
    )

    # Coverage: fraction of markets per time step (vs peak), measured at Y=0 right-tail.
    # Used only to drop degenerate boundary time steps.
    zero_idx = int(np.searchsorted(y_grid, 0.0, side="left"))
    peak_all = float(Z_all[zero_idx, :].max()) or 1.0
    coverage = Z_all[zero_idx, :] / peak_all

    # Drop degenerate boundary time steps before smoothing.
    t_arr = np.array(t_vals, dtype=int)
    keep = (coverage > 0) & (t_arr < args.market_seconds) & (t_arr > 0)
    dropped = t_arr[~keep].tolist()
    if dropped:
        print(f"  Dropping {len(dropped)} degenerate time step(s): {dropped}", flush=True)
    t_vals   = t_arr[keep].tolist()
    Z_up     = Z_up[:, keep]
    Z_isum   = Z_isum[:, keep]
    Z_icnt   = Z_icnt[:, keep]
    Z_all    = Z_all[:, keep]
    coverage = coverage[keep]

    # Smooth numerator and denominator independently before dividing.
    # sigma_y fills sparse extreme buckets (preventing collapse at ±0.40% edges).
    # sigma_t reduces per-time-step noise.
    print("Smoothing and computing conditional probabilities ...", flush=True)
    Z_real_s = smooth_and_divide(Z_up,   Z_all,  args.sigma_y, args.sigma_t)
    Z_impl_s = smooth_and_divide(Z_isum, Z_icnt, args.sigma_y, args.sigma_t)
    Z_gap    = Z_real_s - Z_impl_s

    print_self_check(
        Z_real_s=Z_real_s,
        Z_impl_s=Z_impl_s,
        Z_all_count=Z_all,
        Z_up_count=Z_up,
        coverage=coverage,
    )

    X = np.array(t_vals, dtype=float)
    Y = y_grid.astype(float)

    print("Building ECharts-GL payload ...", flush=True)
    payload = surface_payload(
        X=X,
        Y=Y,
        Z_real_s=Z_real_s,
        Z_impl_s=Z_impl_s,
        Z_gap=Z_gap,
        Z_up_count=Z_up,
        Z_all_count=Z_all,
        Z_impl_count=Z_icnt,
        total_up=total_up,
        market_seconds=args.market_seconds,
        implied_universe=args.implied_universe,
        bucket_width=args.bucket_width,
    )

    print("Writing HTML ...", flush=True)
    out = args.docs / args.out
    out.write_text(build_html(payload), encoding="utf-8")
    print(f"  Saved: {out}")
    print("\nAll done.")


if __name__ == "__main__":
    main()
